name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run gradle build & publish
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish --stacktrace
        env:
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
          CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
